import{a as v,S as L,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function S(t,r,s){return(await v.get("https://pixabay.com/api/",{params:{key:"50311128-48dd02331c2e5a3f7eb5afcac",q:t,page:r,per_page:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more"),C=new L(".gallery a",{captionsData:"alt",captionDelay:250});function B(t){const r=t.map(s=>{const{webformatURL:i,largeImageURL:e,tags:o,likes:a,views:h,comments:b,downloads:w}=s;return`
      <li class="gallery-item">
        <a href="${e}"><img class="gallery-image" src="${i}" alt="${o}"/></a>
        <div class="stats">
          <p><span>Likes</span><span>${a}</span></p>
          <p><span>Views</span><span>${h}</span></p>
          <p><span>Comments</span><span>${b}</span></p>
          <p><span>Downloads</span><span>${w}</span></p>
        </div>
      </li>
        `}).join("");p.insertAdjacentHTML("beforeend",r),C.refresh()}function M(){p.innerHTML=""}function $(){m.style.visibility="visible"}function q(){m.style.visibility="hidden"}function O(){f.style.visibility="visible"}function y(){f.style.visibility="hidden"}const P=document.querySelector(".form"),x=document.querySelector(".load-more");let l,n=1;const u=15;let d="";P.addEventListener("submit",t=>{t.preventDefault(),y(),M(),l=t.target.elements["search-text"].value.trim(),g(l)});x.addEventListener("click",t=>{y(),g(l)});async function g(t){if(t){$(),d!==t&&(n=1,d=t);try{const r=await S(t,n,u),s=r.hits;s&&s.length>0?(B(s),n>=Math.ceil(r.totalHits/u)?c.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",titleColor:"white",backgroundColor:"#4CAF50",position:"topRight"}):O()):c.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",titleColor:"white",backgroundColor:"#ef4040",position:"topRight"}),n++,I()}catch(r){console.error(r)}finally{q()}}}function I(){const t=document.querySelector(".gallery-item");t&&setTimeout(()=>{scrollBy({top:t.getBoundingClientRect().height*2,left:0,behavior:"smooth"})},200)}
//# sourceMappingURL=index.js.map
